### ISSUE TITLE
TypeError: Cannot read property 'execute' of undefined

### ISSUE THREAD

**Issue by whyrmph** [fsalinas26/cpp-login-menu#4]
Hi, NodeJS Server returns an error **TypeError: Cannot read property 'execute' of undefined**
![image](https://user-images.githubusercontent.com/57942975/147304262-a75645e7-3d30-461e-9f92-9f159d2ee881.png)

I send REST API Request 
![image](https://user-images.githubusercontent.com/57942975/147304226-b1cd9a7b-3551-4c78-bd5d-339908c41877.png)
![image](https://user-images.githubusercontent.com/57942975/147304252-47bbe876-0b92-4314-8223-fa59b9c990c4.png)

Am I doing something wrong, or is there a mistake?
How to fix it?

**Comment by fsalinas26** [comment]
Change content-type to **application/x-www-form-urlencoded**

**Comment by ZettaiKotori** [comment]
> Change content-type to **application/x-www-form-urlencoded**

No worked. the problem persists

**Comment by fsalinas26** [comment]
Going to try and replicate this issue in Postman to see what's going on. Thanks for bringing this to my attention.

**Comment by fsalinas26** [comment]
The content of the body must be in **JSON** format because it is a POST request, not a GET.
